included:
  - Sources
  - Tests
excluded:
  - Tests/KeycardTests/XCTestManifests.swift
  - Tests/LinuxMain.swift
file_name:
  excluded:
    - Package.swift
identifier_name:
  excluded:
    - p1
    - p2
